jenkins

diff --git a/Jenkinsfile.bkp b/Jenkinsfile.bkp
--- a/Jenkinsfile.bkp
+++ b/Jenkinsfile.bkp
@@ -1,133 +1,169 @@
 pipeline {
+    // These are pre-build sections
     agent {
         node {
             label 'AGENT-1'
         }
     }
-
     environment {
-        COURSE    = "Jenkins"
+        COURSE = "Jenkins"
         appVersion = ""
-        ACC_ID    = "319625659730"
-        PROJECT   = "roboshop"
+        ACC_ID = "319625659730"
+        PROJECT = "roboshop"
         COMPONENT = "catalogue"
-        GITHUB_OWNER = "nediminenipavan"
-        GITHUB_REPO  = "catalogue"
-        GITHUB_API   = "https://api.github.com"
     }
-
     options {
-        timeout(time: 10, unit: 'MINUTES')
+        timeout(time: 10, unit: 'MINUTES') 
         disableConcurrentBuilds()
     }
-
+    // This is build section
     stages {
-
         stage('Read Version') {
             steps {
-                script {
+                script{
                     def packageJSON = readJSON file: 'package.json'
                     appVersion = packageJSON.version
-                    echo "App Version: ${appVersion}"
+                    echo "app version: ${appVersion}"
                 }
             }
         }
-
         stage('Install Dependencies') {
             steps {
-                sh 'npm install'
-            }
-        }
-
-        stage('Unit Test') {
-            steps {
-                sh 'npm test'
-            }
-        }
-
-        stage('Sonar Scan') {
-            environment {
-                scannerHome = tool 'sonar-8.0'
-            }
-            steps {
-                withSonarQubeEnv('sonar-server') {
-                    sh "${scannerHome}/bin/sonar-scanner"
+                script{
+                    sh """
+                        npm install
+                    """
                 }
             }
         }
-
+        stage('Unit Test') {
+            steps {
+                script{
+                    sh """
+                        npm test
+                    """
+                }
+            }
+        }
+        //Here you need to select scanner tool and send the analysis to server
+        /* stage('Sonar Scan'){
+            environment {
+                def scannerHome = tool 'sonar-8.0'
+            }
+            steps {
+                script{
+                    withSonarQubeEnv('sonar-server') {
+                        sh  "${scannerHome}/bin/sonar-scanner"
+                    }
+                }
+            }
+        }
         stage('Quality Gate') {
             steps {
                 timeout(time: 1, unit: 'HOURS') {
-                    waitForQualityGate abortPipeline: true
+                    // Wait for the quality gate status
+                    // abortPipeline: true will fail the Jenkins job if the quality gate is 'FAILED'
+                    waitForQualityGate abortPipeline: true 
                 }
             }
-        }
-
+        } */
         stage('Dependabot Security Gate') {
             environment {
+                GITHUB_OWNER = 'nediminenipavan'
+                GITHUB_REPO  = 'catalogue'
+                GITHUB_API   = 'https://api.github.com'
                 GITHUB_TOKEN = credentials('GITHUB_TOKEN')
             }
+
             steps {
-                sh '''
-                response=$(curl -s \
-                  -H "Authorization: token $GITHUB_TOKEN" \
-                  -H "Accept: application/vnd.github+json" \
-                  "$GITHUB_API/repos/$GITHUB_OWNER/$GITHUB_REPO/dependabot/alerts?per_page=100")
+                script{
+                    /* Use sh """ when you want to use Groovy variables inside the shell.
+                    Use sh ''' when you want the script to be treated as pure shell. */
+                    sh '''
+                    echo "Fetching Dependabot alerts..."
 
-                high_critical_open_count=$(echo "$response" | jq '[.[] |
-                  select(.state=="open" and
-                  (.security_advisory.severity=="high" or .security_advisory.severity=="critical"))
-                ] | length')
+                    response=$(curl -s \
+                        -H "Authorization: token ${GITHUB_TOKEN}" \
+                        -H "Accept: application/vnd.github+json" \
+                        "${GITHUB_API}/repos/${GITHUB_OWNER}/${GITHUB_REPO}/dependabot/alerts?per_page=100")
 
-                echo "Open HIGH/CRITICAL alerts: $high_critical_open_count"
+                    echo "${response}" > dependabot_alerts.json
 
-                if [ "$high_critical_open_count" -gt 0 ]; then
-                  echo "❌ Blocking pipeline"
-                  exit 1
-                fi
-                '''
+                    high_critical_open_count=$(echo "${response}" | jq '[.[] 
+                        | select(
+                            .state == "open"
+                            and (.security_advisory.severity == "high"
+                                or .security_advisory.severity == "critical")
+                        )
+                    ] | length')
+
+                    echo "Open HIGH/CRITICAL Dependabot alerts: ${high_critical_open_count}"
+
+                    if [ "${high_critical_open_count}" -gt 0 ]; then
+                        echo "❌ Blocking pipeline due to OPEN HIGH/CRITICAL Dependabot alerts"
+                        echo "Affected dependencies:"
+                        echo "$response" | jq '.[] 
+                        | select(.state=="open" 
+                        and (.security_advisory.severity=="high" 
+                        or .security_advisory.severity=="critical"))
+                        | {dependency: .dependency.package.name, severity: .security_advisory.severity, advisory: .security_advisory.summary}'
+                        exit 1
+                    else
+                        echo "✅ No OPEN HIGH/CRITICAL Dependabot alerts found"
+                    fi
+                    '''
+                    
+                }
             }
         }
 
         stage('Build Image') {
             steps {
-                withAWS(region:'us-east-1', credentials:'aws-creds') {
+                script{
+                    withAWS(region:'us-east-1',credentials:'aws-creds') {
+                        sh """
+                            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${ACC_ID}.dkr.ecr.us-east-1.amazonaws.com
+                            docker build -t ${ACC_ID}.dkr.ecr.us-east-1.amazonaws.com/${PROJECT}/${COMPONENT}:${appVersion} .
+                            docker images
+                            docker push ${ACC_ID}.dkr.ecr.us-east-1.amazonaws.com/${PROJECT}/${COMPONENT}:${appVersion}
+                        """
+                    }
+                }
+            }
+        }
+        stage('Trivy Scan'){
+            steps {
+                script{
                     sh """
-                    aws ecr get-login-password --region us-east-1 |
-                    docker login --username AWS --password-stdin ${ACC_ID}.dkr.ecr.us-east-1.amazonaws.com
-
-                    docker build -t ${ACC_ID}.dkr.ecr.us-east-1.amazonaws.com/${PROJECT}/${COMPONENT}:${appVersion} .
-                    docker push ${ACC_ID}.dkr.ecr.us-east-1.amazonaws.com/${PROJECT}/${COMPONENT}:${appVersion}
+                        trivy image \
+                        --scanners vuln \
+                        --severity HIGH,CRITICAL,MEDIUM \
+                        --pkg-types os \
+                        --exit-code 1 \
+                        --format table \
+                        ${ACC_ID}.dkr.ecr.us-east-1.amazonaws.com/${PROJECT}/${COMPONENT}:${appVersion}
                     """
                 }
             }
         }
 
-        stage('Trivy Scan') {
-            steps {
-                sh """
-                trivy image \
-                --severity HIGH,CRITICAL,MEDIUM \
-                --exit-code 1 \
-                ${ACC_ID}.dkr.ecr.us-east-1.amazonaws.com/${PROJECT}/${COMPONENT}:${appVersion}
-                """
-            }
-        }
     }
 
-    post {
-        always {
+        
+
+    post{
+        always{
+            echo 'I will always say Hello again!'
             cleanWs()
         }
         success {
-            echo 'Pipeline succeeded'
+            echo 'I will run if success'
         }
         failure {
-            echo 'Pipeline failed'
+            echo 'I will run if failure'
         }
         aborted {
-            echo 'Pipeline aborted'
+            echo 'pipeline is aborted'
         }
     }
-} 
+}
